Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,23 +1,24 @@
 #!/usr/bin/env bash
-
-#+    The path to the file to be transferred.
-#+    The IP of the server to transfer the file to.
-#+    The username that scp connects with.
-#+    The path to the SSH private key that scp uses.
 #Script that transfers a file from our client to a server
 
-# Check if all parameters are provided
-if [ $# -lt 4 ]; then
-  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-  exit 1
+# Check if all 4 parameters are provided
+if [ "$#" -ne 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
 fi
 
-file_path=$1
+# Assign parameters to variables
+path_to_file=$1
 server_ip=$2
 username=$3
 ssh_key=$4
 
-# Transfer the file using scp
-scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
+# Transfer file using scp
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$server_ip":~/ 
 
-exit 0
+# Check if scp command executed successfully
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully to $username@$server_ip:~/"
+else
+    echo "Error transferring file."
+fi
